apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookservice
  labels:
    app: bookservice
spec:
  selector:
    matchLabels:
      app: bookservice
  replicas: 2
  template:
    metadata:
      labels:
        app: bookservice
    spec:
      containers:
      - name: bookservice
        image: karlguo/book_service_image
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        livenessProbe:
          httpGet:
            path: /status
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5